# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # v3.3.2
      with:
        gradle-version: '8.7'

    - name: Build mn-getting-started
      run: gradle clean build
      working-directory: ./Learn-Micronaut-v4/mn-getting-started

    - name: Build mn-products
      run: gradle clean build
      working-directory: ./Learn-Micronaut-v4/mn-products

    - name: Build mn-web-socket
      run: gradle clean build
      working-directory: ./Learn-Micronaut-v4/mn-web-socket
    
    - name: Build mn-rate-limit
      run: gradle clean build
      working-directory: ./Learn-Micronaut-v4/mn-rate-limit
